# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import log_service_pb2 as log__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in log_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LogServiceStub(object):
    """LogService 日志服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteLog = channel.unary_unary(
                '/logservice.LogService/WriteLog',
                request_serializer=log__service__pb2.WriteLogRequest.SerializeToString,
                response_deserializer=log__service__pb2.WriteLogResponse.FromString,
                _registered_method=True)
        self.BatchWriteLog = channel.unary_unary(
                '/logservice.LogService/BatchWriteLog',
                request_serializer=log__service__pb2.BatchWriteLogRequest.SerializeToString,
                response_deserializer=log__service__pb2.BatchWriteLogResponse.FromString,
                _registered_method=True)
        self.QueryLog = channel.unary_unary(
                '/logservice.LogService/QueryLog',
                request_serializer=log__service__pb2.QueryLogRequest.SerializeToString,
                response_deserializer=log__service__pb2.QueryLogResponse.FromString,
                _registered_method=True)


class LogServiceServicer(object):
    """LogService 日志服务定义
    """

    def WriteLog(self, request, context):
        """WriteLog 写入单条日志
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchWriteLog(self, request, context):
        """BatchWriteLog 批量写入日志
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryLog(self, request, context):
        """QueryLog 查询日志
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteLog': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteLog,
                    request_deserializer=log__service__pb2.WriteLogRequest.FromString,
                    response_serializer=log__service__pb2.WriteLogResponse.SerializeToString,
            ),
            'BatchWriteLog': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchWriteLog,
                    request_deserializer=log__service__pb2.BatchWriteLogRequest.FromString,
                    response_serializer=log__service__pb2.BatchWriteLogResponse.SerializeToString,
            ),
            'QueryLog': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryLog,
                    request_deserializer=log__service__pb2.QueryLogRequest.FromString,
                    response_serializer=log__service__pb2.QueryLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logservice.LogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('logservice.LogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LogService(object):
    """LogService 日志服务定义
    """

    @staticmethod
    def WriteLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logservice.LogService/WriteLog',
            log__service__pb2.WriteLogRequest.SerializeToString,
            log__service__pb2.WriteLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchWriteLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logservice.LogService/BatchWriteLog',
            log__service__pb2.BatchWriteLogRequest.SerializeToString,
            log__service__pb2.BatchWriteLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logservice.LogService/QueryLog',
            log__service__pb2.QueryLogRequest.SerializeToString,
            log__service__pb2.QueryLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
